# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: book_motocycle_api_development

  username: book_motocycle_api

  password: root

test:
  <<: *default
  database: book_motocycle_api_development
  username: book_motocycle_api
  host: localhost
  password: root
  
production:
  <<: *default
  database: book_motocycle_api_production
  username: book_motocycle_api
  password: <%= ENV["BOOK_MOTOCYCLE_API_DATABASE_PASSWORD"] %>
